#!/usr/bin/env php
<?php

(@include_once __DIR__.'/vendor/autoload.php') || @include_once __DIR__.'/../../autoload.php';

use Bab\RabbitMq\Command\VhostMappingCreateCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new VhostMappingCreateCommand());
$application->run();
